Django Basics/Travelers Hub Application/TravelersHubApplication/common/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('all-trips/', views.all_trips, name='all-trips'),
]

Django Basics/Travelers Hub Application/TravelersHubApplication/traveler/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_traveler, name='create-traveler'),
    path('edit/<int:traveler_id>/', views.edit_traveler, name='edit-traveler'),
    path('details/<int:traveler_id>/', views.details_traveler, name='details-traveler'),
    path('delete/<int:traveler_id>/', views.delete_traveler, name='delete-traveler'),
]

Django Basics/Travelers Hub Application/TravelersHubApplication/trip/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_trip, name='create-trip'),
    path('<int:trip_id>/edit/', views.edit_trip, name='edit-trip'),
    path('<int:trip_id>/delete/', views.delete_trip, name='delete-trip'),
    path('<int:trip_id>/details/', views.details_trip, name='details-trip'),
]

Django Basics/Travelers Hub Application/TravelersHubApplication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TravelersHubApplication.common.urls')),
    path('traveler/', include('TravelersHubApplication.traveler.urls')),
    path('trips/', include('TravelersHubApplication.trip.urls')),
]

Django Basics/Travelers Hub Application/TravelersHubApplication/common/models.py
from django.db import models

# Create your models here.

Django Basics/Travelers Hub Application/TravelersHubApplication/traveler/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re

def validate_nickname(value):
    if not re.match(r'^[a-zA-Z0-9]+$', value):
        raise ValidationError('Your nickname is invalid!')

class Traveler(models.Model):
    nickname = models.CharField(
        max_length=30,
        unique=True,
        validators=[validate_nickname],
        help_text="Nicknames can contain only letters and digits."
    )
    email = models.EmailField(
        max_length=30,
        unique=True
    )
    country = models.CharField(
        max_length=3
    )
    about_me = models.TextField(
        blank=True
    )

    def __str__(self):
        return self.nickname

Django Basics/Travelers Hub Application/TravelersHubApplication/trip/models.py
from django.db import models
from django.utils import timezone
from TravelersHubApplication.traveler.models import Traveler

class Trip(models.Model):
    destination = models.CharField(
        max_length=100
    )
    summary = models.TextField()
    start_date = models.DateField(
        default=timezone.now
    )
    duration = models.PositiveSmallIntegerField(
        default=1,
        help_text="Duration in days is expected."
    )
    image_url = models.URLField(
        blank=True
    )
    traveler = models.ForeignKey(
        Traveler, on_delete=models.CASCADE,
        related_name='trips'
    )

    def __str__(self):
        return f"{self.destination} - {self.start_date}"

Django Basics/Travelers Hub Application/TravelersHubApplication/traveler/forms.py
from django import forms
from .models import Traveler

class TravelerForm(forms.ModelForm):
    class Meta:
        model = Traveler
        fields = ['nickname', 'email', 'country', 'about_me']

Django Basics/Travelers Hub Application/TravelersHubApplication/trip/forms.py
from django import forms
from .models import Trip

class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['destination', 'summary', 'start_date', 'duration', 'image_url']

Django Basics/Travelers Hub Application/TravelersHubApplication/common/views.py
from django.shortcuts import render, redirect
from TravelersHubApplication.traveler.models import Traveler
from TravelersHubApplication.trip.models import Trip

def get_profile():
    return Traveler.objects.first()

def index_with_profile(request):
    traveler = get_profile()

    if traveler:
        trips = Trip.objects.filter(traveler=traveler).order_by('-start_date')
        context = {
            'traveler': traveler,
            'trips': trips,
        }
        return render(request, "index.html", context)

    return redirect('index')


def index(request):
    traveler = get_profile()

    if traveler is None:
        return render(request, 'index.html', {'traveler': None})

    return index_with_profile(request)

def all_trips(request):
    traveler = get_profile()

    if traveler:
        trips = Trip.objects.filter(traveler=traveler).order_by('-start_date')
        context = {
            'traveler': traveler,
            'trips': trips,
        }
        return render(request, "all-trips.html", context)

    return redirect('index')

Django Basics/Travelers Hub Application/TravelersHubApplication/traveler/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TravelerForm
from .models import Traveler
from ..trip.models import Trip


def create_traveler(request):
    if request.method == 'POST':
        form = TravelerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = TravelerForm()
    return render(request, 'create-traveler.html', {'form': form})

def edit_traveler(request, traveler_id):
    traveler = Traveler.objects.get(id=traveler_id)
    if request.method == 'POST':
        form = TravelerForm(request.POST, instance=traveler)
        if form.is_valid():
            form.save()
            return redirect('details-traveler', traveler_id=traveler.id)
    else:
        form = TravelerForm(instance=traveler)
    return render(request, 'edit-traveler.html', {'form': form})


def details_traveler(request, traveler_id):
    traveler = get_object_or_404(Traveler, id=traveler_id)
    trips = Trip.objects.filter(traveler=traveler).order_by('-start_date')

    return render(request, 'details-traveler.html', {
        'traveler': traveler,
        'trips': trips,
        'traveler_id': traveler.id,
    })


def delete_traveler(request, traveler_id):
    traveler = get_object_or_404(Traveler, id=traveler_id)

    if request.method == 'POST':
        print(f"Deleting traveler with ID {traveler_id}")
        traveler.trips.all().delete()
        traveler.delete()
        print("Traveler and trips deleted.")
        return redirect('index')

    return render(request, 'delete-traveler.html', {'traveler': traveler})


Django Basics/Travelers Hub Application/TravelersHubApplication/trip/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TripForm
from .models import Trip
from ..common.views import get_profile


def create_trip(request):
    traveler = get_profile()

    if not traveler:
        return redirect('create-traveler')

    if request.method == 'POST':
        form = TripForm(request.POST)
        if form.is_valid():

            trip = form.save(commit=False)
            trip.traveler = traveler
            trip.save()

            return redirect('all-trips')
    else:
        form = TripForm()

    return render(request, 'create-trip.html', {'form': form, 'traveler': traveler})


def edit_trip(request, trip_id):
    traveler = get_profile()

    if not traveler:
        return redirect('create-traveler')

    trip = get_object_or_404(Trip, id=trip_id)

    if request.method == 'POST':
        form = TripForm(request.POST, instance=trip)
        if form.is_valid():
            form.save()
            return redirect('all-trips')

    else:
        form = TripForm(instance=trip)

    context = {
        'form': form,
        'traveler': traveler,
    }

    return render(request, 'edit-trip.html', context)

def delete_trip(request, trip_id):
    traveler = get_profile()

    if not traveler:
        return redirect('create-traveler')

    trip = get_object_or_404(Trip, id=trip_id)

    if request.method == 'POST':
        trip.delete()  # Delete the trip
        return redirect('all-trips')

    return render(request, 'delete-trip.html', {'trip': trip, 'traveler': traveler})


def details_trip(request, trip_id):
    traveler = get_profile()

    if not traveler:
        return redirect('create-traveler')

    trip = get_object_or_404(Trip, id=trip_id)

    return render(request, 'details-trip.html', {'trip': trip, 'traveler': traveler})

Django Basics/Travelers Hub Application/templates/all-trips.html
{% extends 'base.html' %}

{% block title %}All Trips - Travelers Hub{% endblock %}

{% block content %}
    <!-- All Trips page -->
<main>
    {% if trips.exists %}
        <h2>{{ trips.count }} Shared Trips</h2>
    <section id="dashboard">
        <!-- Display a heading if there are trips, including their count -->
        {% for trip in trips %}
            <div class="post">
                <!-- trip image if there is such, otherwise display the default one -->
                <img src="{{ trip.image_url|default:'/static/images/default-trip.jpg' }}" alt="{{ trip.destination }} img" />

                <!-- trip destination -->
                <h3 class="title">{{ trip.destination }}</h3>
                <!-- trip start date in format "D d M Y" -->
                <p class="description">{{ trip.start_date|date:"D d M Y" }}</p>
                <!-- trip details button -->
                <a class="details-btn" href="/trips/{{ trip.pk }}/details/">Details</a>
            </div>
        {% endfor %}
    {% else %}
        <!-- Display a heading if there are NO trips -->
    <h2>No shared trips</h2>
    {% endif %}
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <title>Traveler's Hub</title>
</head>
<body>
    <div id="wrapper">
        {% include "navbar.html" %}
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </div>
    <!-- footer -->
    {% include "footer.html" %}
</body>
</html>

Django Basics/Travelers Hub Application/templates/create-traveler.html
{% extends 'base.html' %}

{% block title %}New Traveler's Profile - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="register">
        <div class="form">
            <h2>New Traveler's Profile</h2>
            <form class="register-form" method="post" action="">
                {% csrf_token %}
                <div>
                    <label for="id_nickname">Nickname:</label>
                    <div class="helptext" id="id_nickname_helptext">*Nicknames can contain only letters and digits.</div>
                    <input type="text" name="nickname" maxlength="30" placeholder="Enter a unique nickname..."
                        required aria-describedby="id_nickname_helptext" id="id_nickname">
                </div>
                <div>
                    <label for="id_email">Email:</label>
                    <input type="email" name="email" maxlength="30" placeholder="Enter a valid email address..."
                        required id="id_email">
                </div>
                <div>
                    <label for="id_country">Country:</label>
                    <input type="text" name="country" maxlength="3" placeholder="Enter a country code like &lt;BGR&gt;..."
                        required id="id_country">
                </div>
                <button type="submit">Create</button>
            </form>
        </div>
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/create-trip.html
{% extends 'base.html' %}

{% block title %}Share a New Trip - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="create">
        <div class="form">
            <h2>Share a New Trip</h2>
            <form class="create-form" action="" method="post">
                {% csrf_token %}
                <div>
                    <label for="id_destination">Destination:</label>
                    <input type="text" name="destination" maxlength="100"
                        placeholder="Enter a short destination note..." required id="id_destination">
                </div>
                <div>
                    <label for="id_summary">Summary:</label>
                    <textarea name="summary" cols="40" rows="10" placeholder="Share your exciting moments..."
                        required id="id_summary"></textarea>
                </div>
                <div>
                    <label for="id_start_date">Started on:</label>
                    <input type="date" name="start_date" required id="id_start_date">
                </div>
                <div>
                    <label for="id_duration">Duration:</label>
                    <div class="helptext" id="id_duration_helptext">*Duration in days is expected.</div>
                    <input type="number" name="duration" value="1" min="0" required
                        aria-describedby="id_duration_helptext" id="id_duration">
                </div>
                <div>
                    <label for="id_image_url">Image URL:</label>
                    <input type="url" name="image_url" maxlength="200" placeholder="An optional image URL..."
                        id="id_image_url">
                </div>
                <button type="submit">Share</button>
            </form>
        </div>
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/delete-traveler.html
{% extends 'base.html' %}

{% block title %}Delete Traveler's Profile - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="edit">
        <div class="form">
            <h1>Do you like to delete your Traveler's Profile? {{ traveler.nickname }}</h1>
            <form id='delete' class="delete-confirmation" method="post" action="">
                {% csrf_token %}
                <button type="submit">Yes</button>
            </form>
        </div>
    </section>
</main>
{% endblock %}


Django Basics/Travelers Hub Application/templates/delete-trip.html
{% extends 'base.html' %}

{% block title %}Delete Trip - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="edit">
        <div class="form">
            <h2>Delete Trip</h2>
            <form class="edit-form" method="post" action="">
                {% csrf_token %}
                <div>
                    <label for="id_destination">Destination:</label>
                    <input type="text" name="destination" value="{{ trip.destination }}" maxlength="100" readonly="readonly"
                        required id="id_destination">
                </div>
                <div>
                    <label for="id_summary">Summary:</label>
                    <textarea name="summary" cols="40" rows="10" readonly="readonly" required id="id_summary">{{ trip.summary }}</textarea>
                </div>
                <div>
                    <label for="id_start_date">Started on:</label>
                    <input type="date" name="start_date" value="{{ trip.start_date }}" readonly="readonly" required
                        id="id_start_date">
                </div>
                <div>
                    <label for="id_duration">Duration:</label>
                    <div class="helptext" id="id_duration_helptext">*Duration in days is expected.</div>
                    <input type="number" name="duration" value="{{ trip.duration }}" min="0" readonly="readonly" required
                        aria-describedby="id_duration_helptext" id="id_duration">
                </div>
                <div>
                    <label for="id_image_url">Image URL:</label>
                    <input type="url" name="image_url" value="{{ trip.image_url }}" maxlength="200" readonly="readonly" id="id_image_url">
                </div>
                <button type="submit">Delete</button>
            </form>
        </div>
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/details-traveler.html
{% extends 'base.html' %}

{% block title %}Traveler's Profile - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="details">
        <div id="details-wrapper">
            <h2>Traveler's Profile</h2>

            <!-- Traveler's image -->
            <img id="details-img" src="{{ traveler.image_url|default:'/static/images/default-traveler.png' }}" alt="profile img" />

            <!-- Traveler's nickname -->
            <p id="details-title">{{ traveler.nickname }}</p>

            <!-- Traveler's email and country -->
            <p id="nutrition"><span>Email: </span>{{ traveler.email }}<span> Country: </span>{{ traveler.country }}</p>

            <div id="info-wrapper">
                <div id="details-description">

                    <!-- About me section -->
                    {% if traveler.about_me %}
                        <p><span>About me: </span>{{ traveler.about_me }}</p>
                    {% endif %}

                    <!-- Shared trips section -->
                    {% if trips.exists %}
                        <p><span>Shared Trips:</span></p>
                        <ul>
                            {% for trip in trips %}
                                <li>{{ trip.destination }}: {{ trip.duration }} day/s, started on: {{ trip.start_date|date:"Y-m-d" }}</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p><span>Shared Trips:</span> No trips shared yet.</p>
                    {% endif %}

                </div>
                <!-- Edit and Delete buttons -->
                <div id="action-buttons">
                    <a href="{% url 'edit-traveler' traveler_id %}" id="edit-btn">Edit</a>
                    <a href="{% url 'delete-traveler' traveler_id %}" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/details-trip.html
{% extends 'base.html' %}

{% block title %}Trip Details - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="details">
        <div id="details-wrapper">
            <h2>Trip Details</h2>

            <!-- Trip image -->
            <img src="{{ trip.image_url|default:'https://cdn.pixabay.com/photo/2021/10/05/16/53/kimono-6683245_1280.jpg' }}" alt="{{ trip.destination }} img" />

            <!-- Trip destination -->
            <p id="details-title">{{ trip.destination }}</p>

            <div id="info-wrapper">
                <div id="details-description">

                    <!-- Trip start date -->
                    <p class="description">{{ trip.start_date|date:"D d M Y" }}</p>

                    <!-- Trip duration -->
                    <p>{{ trip.duration }} day/s</p>

                    <!-- Trip summary -->
                    <p>{{ trip.summary }}</p>
                </div>

                <!-- Edit and Delete buttons -->
                <div id="action-buttons">
                    <a href="/trips/{{ trip.pk }}/edit/" id="edit-btn">Edit</a>
                    <a href="/trips/{{ trip.pk }}/delete/" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/edit-traveler.html
{% extends 'base.html' %}

{% block title %}Edit Traveler's Profile - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="register">
        <div class="form">
            <h2>Edit Traveler's Profile</h2>
            <form class="register-form" method="post" action="">
                {% csrf_token %}
                <div>
                    <label for="id_nickname">Nickname:</label>

                    <div class="helptext" id="id_nickname_helptext">*Nicknames can contain only letters and digits.</div>

                    <input type="text" name="nickname" value="{{ traveler.nickname }}" maxlength="30" required
                        aria-describedby="id_nickname_helptext" id="id_nickname">

                </div>

                <div>
                    <label for="id_email">Email:</label>

                    <input type="email" name="email" value="{{ traveler.email }}" maxlength="30" required
                        id="id_email">

                </div>

                <div>
                    <label for="id_country">Country:</label>

                    <input type="text" name="country" value="{{ traveler.country }}" maxlength="3" required id="id_country">

                </div>

                <div>
                    <label for="id_about_me">About me:</label>

                    <textarea name="about_me" cols="40" rows="10" id="id_about_me">{{ traveler.about_me }}</textarea>

                </div>

                <button type="submit">Edit</button>

            </form>
        </div>
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/edit-trip.html
{% extends 'base.html' %}

{% block title %}Edit Trip - Travelers Hub{% endblock %}

{% block content %}
<main>
    <section id="edit">
        <div class="form">
            <h2>Edit Trip</h2>
            <form class="edit-form" method="post" action="">
                {% csrf_token %}
                <div>
                    <label for="id_destination">Destination:</label>

                    <input type="text" name="destination" value="{{ trip.destination }}" maxlength="100" required
                        id="id_destination">

                </div>

                <div>
                    <label for="id_summary">Summary:</label>

                    <textarea name="summary" cols="40" rows="10" required id="id_summary">{{ trip.summary }}</textarea>

                </div>

                <div>
                    <label for="id_start_date">Started on:</label>

                    <input type="date" name="start_date" value="{{ trip.start_date }}" required id="id_start_date">

                </div>

                <div>
                    <label for="id_duration">Duration:</label>

                    <div class="helptext" id="id_duration_helptext">*Duration in days is expected.</div>

                    <input type="number" name="duration" value="{{ trip.duration }}" min="0" required
                        aria-describedby="id_duration_helptext" id="id_duration">

                </div>

                <div>
                    <label for="id_image_url">Image URL:</label>

                    <input type="url" name="image_url" value="{{ trip.image_url }}" maxlength="200" id="id_image_url">

                </div>

                <button type="submit">Edit</button>
            </form>
        </div>
    </section>
</main>
{% endblock %}

Django Basics/Travelers Hub Application/templates/footer.html
{% load static %}
    <!-- footer -->
    <footer>
        <p>&copy; 2024 Travelers Hub by SoftUni Team. All rights reserved.</p>
    </footer>

Django Basics/Travelers Hub Application/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Traveler's Hub{% endblock %}

{% block content %}
    <!-- Home page -->
    <section id="home">
        <h1 class="main-title">Wander, Explore, Share...</h1>
        <img src="{% static 'images/logo-img-trip.png' %}" alt="Traveler's Hub Logo" class="logo-img">
    <!-- If there is a traveler's profile -->
        {% if traveler %}
            
        {% else %}

        {% endif %}
    </section>
{% endblock %}

Django Basics/Travelers Hub Application/templates/navbar.html
{% load static %}

<header>
    <a id="logo" href="{% url 'index' %}">
        <img id="logo-img" src="{% static 'images/logo-boeing.png' %}" alt="logo" />
    </a>
    <nav>
        <div class="user">
            {% if traveler %}
                    <a href="{% url 'all-trips' %}">All Trips</a>
                    <a href="{% url 'create-trip' %}">Share Trip</a>
                    <a href="{% url 'details-traveler' traveler.id %}">Traveler's Profile</a>
            {% endif %}
        </div>

        <div class="guest">
            {% if not traveler %}
                <a href="{% url 'create-traveler' %}">New Traveler's Profile</a>
            {% endif %}
        </div>
    </nav>
</header>