Django Basics/Exam Preparation/ExamPreparationApp/ExamPreparationApp/profiles/urls.py
from django.urls import path, include

from ExamPreparationApp.profiles.views import DetailProfileView, DeleteProfileView

urlpatterns = (
         path('details/', DetailProfileView.as_view(), name='details_profile'),
         path('delete/', DeleteProfileView.as_view(), name='delete_profile'),
        )

Django Basics/Exam Preparation/ExamPreparationApp/ExamPreparationApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('ExamPreparationApp.web.urls')),
    path('profile/', include('ExamPreparationApp.profiles.urls')),
    path('album/', include('ExamPreparationApp.albums.urls')),
]

Django Basics/Exam Preparation/ExamPreparationApp/ExamPreparationApp/albums/models.py
from django.core.validators import MinValueValidator
from django.db import models

from ExamPreparationApp.profiles.models import Profile

"""· Album

o Album Name
    Character field, required.
    All album names must be unique.
    It should consist of a maximum of 30 characters.

o Artist
    Character field, required.
    It should consist of a maximum of 30 characters.

o Genre
    Character field, required.
    It should consist of a maximum of 30 characters.
    The choices are "Pop Music", "Jazz Music", "R&B Music", "Rock Music", "Country Music", "Dance Music", "Hip Hop Music", and "Other".

o Description
    Text field, optional.

o Image URL
    URL field, required.

o Price
    Float field, required.
    The price cannot be below 0.0.

o Owner
    A foreign key to the Profile model.
    Establishes a many-to-one relationship with the Profile model, associating each album with a profile.
    The ON DELETE constraint must be configured to an appropriate value in alignment with the specified additional tasks.
    This field should remain hidden in forms."""


class Album(models.Model):
    MAX_AlBUM_NAME = 30
    MAX_ARTIST_NAME = 30
    MAX_GENRE_NAME = 30

    MIN_PRICE = 0.0

    GENRE_CHOICES = (
        ("JAZZ MUSIC", "Jazz Music"),
        ("R&B MUSIC", "R&B Music"),
        ("ROCK MUSIC", "Rock Music"),
        ("COUNTRY MUSIC", "Country Music"),
        ("DANCE MUSIC", "Dance Music"),
        ("HIP HOP MUSIC", "Hip Hop Music"),
        ("OTHER", "Other"),

    )
    album_name = models.CharField(
        unique=True,
        max_length=MAX_AlBUM_NAME,
        null=False,
        blank=False,
        verbose_name='Album Name',
    )
    artist = models.CharField(
        max_length=MAX_ARTIST_NAME,
        null=False,
        blank=False,
        verbose_name='Artist',
    )
    genre = models.CharField(
        max_length=MAX_GENRE_NAME,
        null=False,
        blank=False,
        choices=GENRE_CHOICES,
        verbose_name='Genre',
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Description',
    )
    image_url = models.URLField(
        null=False,
        blank=False,
        verbose_name='Image URL',
    )
    price = models.FloatField(
        null=False,
        blank=False,
        validators=(
            MinValueValidator(MIN_PRICE),
        )
    )
    owner = models.ForeignKey(
        to=Profile,
        on_delete=models.CASCADE,
        editable=False,
    )




Django Basics/Exam Preparation/ExamPreparationApp/ExamPreparationApp/profiles/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models

"""
· Profile

o Username
    Character field, required.
    It should have at least 2 characters and maximum - 15 characters.
    The username can consist only of letters, numbers, and underscore ("_"). Otherwise, raise a ValidationError with the message: "Ensure this value contains only letters, numbers, and underscore."

o Email
    Email field, required.

o Age
    Integer field, optional.
    The age cannot be below 0"""


def validate_username(username):
    is_valid = all(ch.isalnum or ch == '_' for ch in username)

    if not is_valid:
        raise ValidationError("Ensure this value contains only letters, numbers, and underscore.")


class Profile(models.Model):
    MIN_USERNAME_LENGTH = 2
    MAX_USERNAME_LENGTH = 15
    username = models.CharField(
        null=False,
        blank=False,
        max_length=MAX_USERNAME_LENGTH,
        validators=(
            MinLengthValidator(MIN_USERNAME_LENGTH),
        )
    )
    email = models.EmailField(
        null=False,
        blank=False,
    )
    age = models.IntegerField(
        null=False,
        blank=False
    )

Django Basics/Exam Preparation/ExamPreparationApp/ExamPreparationApp/profiles/views.py
from django.urls import reverse_lazy
from django.views import generic as views

from ExamPreparationApp.profiles.models import Profile


def get_profile():
    return Profile.objects.first()
    # If this profile exists we cannot create it


class DetailProfileView(views.DetailView):
    queryset = Profile.objects.all()
    template_name = 'profile/profile-details.html'

    def get_object(self, queryset=None):
        return get_profile()


class DeleteProfileView(views.DeleteView):
    template_name = 'profile/profile-delete.html'
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        return get_profile()



Django Basics/Exam Preparation/ExamPreparationApp/templates/profile/profile-delete.html
{% extends 'base.html' %}

{% block main_content %}
      <section id="detailsPage">
        <div class="wrapper">
          <div class="profileText">
            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form action="{% url 'delete_profile' %}" method="post">
              <!-- Confirm Button -->
              <button class="delete-profile" type="submit">Delete</button>
                {% csrf_token %}
            </form>
            <!-- End Delete Profile Form -->
          </div>
        </div>
      </section>

{% endblock %}

Django Basics/Exam Preparation/ExamPreparationApp/templates/profile/profile-details.html
{% extends 'base.html' %}

{% block main_content %}
      <section id="detailsPage">
        <div class="wrapper">
          <div class="profilePage">
            <img
              src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
              alt="Profile Image"
            />
          </div>

          <div class="profileText">
            <!-- Profile Info -->
            <h1>Username: {{ object.username }}</h1>
            <h1>Email: {{ object.email }}</h1>
              {% if object.age %}
            <h1>Age: {{ object.age }}</h1>
              {% endif %}
            <h1>Albums: {{ object.album_set.count }}</h1>
          </div>

          <div class="actionBtn">
            <!-- Button for Deleting the Profile -->
            <a href="{% url 'delete_profile' %}" class="remove">Delete</a>
          </div>
        </div>
      </section>

{% endblock %}